name: Deploy EC2 Instance with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_region: us-east-1

jobs:
  terraform:
    name: Deploy EC2 Instance
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      # Optional: Post-Apply Outputs
      - name: Show Outputs
        run: terraform output
